services:
  - type: static
    name: ton-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build  # ou le dossier où ton build est généré (ex. "dist")
    routes:
      - type: rewrite
        source: /*
        destination: /index.html